sudo: required
services: 
    - docker

before_install:
    - docker build -t jsutersuisse/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true  Johannessuisse/docker-react npm run test